// This file was generated by RedwoodJS
import * as Cell from './EditBlogContentCell'
import type { CellProps } from '@redwoodjs/web'
import type { EditBlogContentById, EditBlogContentByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './EditBlogContentCell'

type CellInputs = CellProps<SuccessType, EditBlogContentById, typeof Cell, EditBlogContentByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
