// This file was generated by RedwoodJS
import * as Cell from './BlogContentsCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindBlogContents, FindBlogContentsVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './BlogContentsCell'

type CellInputs = CellProps<SuccessType, FindBlogContents, typeof Cell, FindBlogContentsVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
