// This file was generated by RedwoodJS
import * as Cell from './BlogContentCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindBlogContentById, FindBlogContentByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './BlogContentCell'

type CellInputs = CellProps<SuccessType, FindBlogContentById, typeof Cell, FindBlogContentByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>

//# sourceMappingURL=index.d.ts.map
