// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/jy/work/123/app/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/Users/jy/work/123/app/web/src/pages/NotFoundPage/NotFoundPage'
import BlogContentBlogContentPageType from '/Users/jy/work/123/app/web/src/pages/BlogContent/BlogContentPage/BlogContentPage'
import BlogContentBlogContentsPageType from '/Users/jy/work/123/app/web/src/pages/BlogContent/BlogContentsPage/BlogContentsPage'
import BlogContentEditBlogContentPageType from '/Users/jy/work/123/app/web/src/pages/BlogContent/EditBlogContentPage/EditBlogContentPage'
import BlogContentNewBlogContentPageType from '/Users/jy/work/123/app/web/src/pages/BlogContent/NewBlogContentPage/NewBlogContentPage'
import PostEditPostPageType from '/Users/jy/work/123/app/web/src/pages/Post/EditPostPage/EditPostPage'
import PostNewPostPageType from '/Users/jy/work/123/app/web/src/pages/Post/NewPostPage/NewPostPage'
import PostPostPageType from '/Users/jy/work/123/app/web/src/pages/Post/PostPage/PostPage'
import PostPostsPageType from '/Users/jy/work/123/app/web/src/pages/Post/PostsPage/PostsPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
  const BlogContentBlogContentPage: typeof BlogContentBlogContentPageType
  const BlogContentBlogContentsPage: typeof BlogContentBlogContentsPageType
  const BlogContentEditBlogContentPage: typeof BlogContentEditBlogContentPageType
  const BlogContentNewBlogContentPage: typeof BlogContentNewBlogContentPageType
  const PostEditPostPage: typeof PostEditPostPageType
  const PostNewPostPage: typeof PostNewPostPageType
  const PostPostPage: typeof PostPostPageType
  const PostPostsPage: typeof PostPostsPageType
}

//# sourceMappingURL=web-routesPages.d.ts.map
